services:
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    environment:
      - NEXT_PUBLIC_API_URL=http://server:3001
    ports:
      - "3000:3000"
    depends_on:
      - server
    networks:
      - rstat-network

  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    env_file:
      - .env
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/postgres
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - rstat-network
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    tmpfs:
      - /var/lib/postgresql/data:rw
    networks:
      - rstat-network

networks:
  rstat-network:
    driver: bridge