name: Release Push Docker Images 

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version:
        description: "Version to build"
        required: true

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - id: get_version
        name: Get version
        continue-on-error: true
        uses: jannemattila/get-version-from-tag@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Images
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/rstat-server:${{ inputs.version || steps.get_version.outputs.version }}
            ${{ secrets.DOCKER_USERNAME }}/rstat-server:latest
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and Push Docker Images
        uses: docker/build-push-action@v4
        with:
          context: frontend
          file: frontend/Dockerfile
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/rstat-frontend:${{ inputs.version || steps.get_version.outputs.version }}
            ${{ secrets.DOCKER_USERNAME }}/rstat-frontend:latest
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
